###
### All Variable like ${var_name} taken from ".env" file
### in the root of the project
###
### Create file ".env" from ".env.tmp"
### and put u variable values
###
### ${DOCKER_LOCALHOST_IP}
### > $(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
###
###
### Delete all containers
### > docker rm $(docker ps -a -q)
###
### Delete all images
### > docker rmi $(docker images -q)
###


version: "3.1"

services:
  
  swift:
    image: swift:5.3.3
    volumes:
      - ./:/app
    command: ["sleep", "infinity"]
    networks:
      - net



networks:
  net:
    driver: bridge


